const $=(selector)=>document.querySelector(selector);
const soundIds=Array.from({length:5},(_,i)=>[`S${i+1}A`,`S${i+1}B`]).flat();
const bIds=['B1','B2','B3'];
const modelDefaults={transfer:{f0:440,q:6},echo:{delay:5,reflection:.6},damping:{f0:440,q:8},reference:{h0:.2,noise:.01,drift:0}};
const state={panel:{planningPanels:[]},sound:{loops:[]},b:{rounds:[]},sources:[],historySources:[],modernSources:[],consciousSources:[],alchemy:null,selected:'S1A',model:'transfer',values:structuredClone(modelDefaults),setup:[]};
const statusLabels={planned:'Planned',frozen:'Contract frozen',executed_pending_review:'Executed · review pending',accepted_narrow:'Accepted within model',rejected_or_repair:'Repair required',completed:'Completed planning'};
const escapeHtml=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=v=>Array.isArray(v)?v:typeof v==='string'&&v?[v]:[];
const plain=v=>typeof v==='string'?v:'';
const cleanStatus=v=>statusLabels[v]?v:'planned';
const linkPath=p=>{if(typeof p!=='string'||!p)return null;if(/^https:\/\//i.test(p))return p;if(/^(?!\/)(?!.*(?:^|\/)\.\.(?:\/|$))[a-zA-Z0-9_.\-/]+$/.test(p))return `../${p}`;return null};
const link=(p,label)=>{const href=linkPath(p);return href?`<a href="${escapeHtml(href)}"${href.startsWith('https://')?' target="_blank" rel="noopener noreferrer"':''}>${escapeHtml(label)} ↗</a>`:''};
const status=v=>`<span class="status ${escapeHtml(cleanStatus(v))}">${escapeHtml(statusLabels[v]||'Planned')}</span>`;
async function readJSON(path){const response=await fetch(new URL(path,import.meta.url));if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);return response.json()}

async function loadResearch(){
 const entries=await Promise.allSettled([
  readJSON('../research/panel-v3-decisions.json'),
  readJSON('../research/sound-lab-v3/summaries.json'),
  readJSON('../research/consciousness-v3/summary.json'),
  readJSON('../research/sound-lab-v3/sources.json'),
  readJSON('../docs/panel-v3/setup-catalog.json'),
  readJSON('../docs/panel-v3/alchemy-dictionary.json'),
  readJSON('../docs/panel-v3/sources-consciousness.json'),
  readJSON('../docs/panel-v3/sources-history.json'),
  readJSON('../docs/panel-v3/sources-modern.json')
 ]);
 if(entries[0].status==='fulfilled')state.panel=entries[0].value;
 if(entries[1].status==='fulfilled')state.sound=entries[1].value;
 if(entries[2].status==='fulfilled')state.b=entries[2].value;
 if(entries[3].status==='fulfilled')state.sources=list(entries[3].value.sources);
 if(entries[4].status==='fulfilled')state.setup=list(entries[4].value.entries);
 if(entries[5].status==='fulfilled')state.alchemy=entries[5].value;
 if(entries[6].status==='fulfilled')state.consciousSources=list(entries[6].value.sources);
 if(entries[7].status==='fulfilled')state.historySources=list(entries[7].value.sources);
 if(entries[8].status==='fulfilled')state.modernSources=list(entries[8].value.sources);
 renderPlanning();renderAmendments();renderLedger();renderRoadmap();renderB();renderSetup();renderAlchemy();renderSourceIndex();renderCli();
}

function renderPlanning(){
 const panels=list(state.panel.planningPanels),container=$('#planning-panels');
 container.innerHTML=['P1','P2','P3'].map((id,i)=>{
  const p=panels.find(x=>x.id===id),label=['Source & feasibility','Skeptical challenge','Question selected'][i];
  return `<article class="panel-card"><div><span class="ordinal">${id}</span>${status(p?.status==='completed'?'completed':'planned')}</div><h3>${escapeHtml(p?.question||label)}</h3><p>${p?'The exchanged submissions and the decision are preserved in the panel record.':'This panel has no recorded decision yet.'}</p>${p?.record?`<div class="artifact-links" style="margin-top:13px">${link(p.record,'Read panel exchange')}</div>`:''}</article>`;
 }).join('');
}
function renderAmendments(){const box=$('#decision-amendments'),records=list(state.panel.decisionAmendments);box.innerHTML=records.map(a=>`<aside class="amendment"><span class="eyebrow">${escapeHtml(a.id)} / recorded course correction after ${escapeHtml(a.afterReview)}</span><p><strong>Earlier candidate:</strong> ${escapeHtml(a.prior)}. <strong>Selected instead:</strong> ${escapeHtml(a.changedTo)}.</p><p>${escapeHtml(a.reason)}</p><p>${escapeHtml(a.reviewPreservation||'Original review remains unchanged.')} ${link(a.recordPath,'Read decision record')}</p></aside>`).join('')}
function renderRoadmap(){const accepted=list(state.panel.reviews).filter(r=>r.status==='accepted_narrow'),sound=accepted.filter(r=>soundIds.includes(r.id)).length,b=accepted.filter(r=>bIds.includes(r.id)).length,next=plain(state.panel.nextAuthorized);$('#research-roadmap').innerHTML=`<h3>What opens next</h3><div class="roadmap-row"><span>01 / sound</span><strong>${sound} of 10 reviewed sound loops</strong><p>${escapeHtml(next||'The ten-loop research gate has no further selection recorded.')}</p></div><div class="roadmap-row"><span>02 / physical</span><strong>Controlled capture remains a separate future task</strong><p>Record original files, geometry, source-off/repeat controls and device settings before using the versioned intake. No physical bench result is in this ledger.</p></div><div class="roadmap-row"><span>03 / conditional B</span><strong>${b} of 3 reviewed method audits</strong><p>B1–B3 follow the sound gate. Any human or live-AI target study requires independent target custody and a preregistered endpoint; no such observation is claimed here.</p></div><p class="roadmap-boundary">${escapeHtml(state.panel.empiricalBoundary||'Synthetic work is not a physical or consciousness measurement.')} ${link('docs/continuation-v3.md','Continuation roadmap')} ${link('docs/panel-v3/advisor-review.md','Independent review record')} ${link('docs/panel-v3/next-gates.md','Future study gates')}</p>`}
function renderCli(){const box=$('#cli-guide'),review=list(state.panel.reviews).find(r=>r.id==='S3A');if(!review||review.status!=='accepted_narrow')return;box.innerHTML=`<h4>Fit a recorded ringdown with the reviewed safe intake</h4><code>python research/sound-lab-v3/intake_v2.py path/to/recording.wav --frequency 500 --start 1.05 --stop 1.8 --output path/to/new-fit</code><p>Run from the repository root after preserving the original. Choose and document the frequency, elapsed-time window, and a new output prefix; the script rejects collisions and existing output files, then writes JSON and fit-trace CSV. Its result describes a recorded channel, not intrinsic material damping. <a href="../research/sound-lab-v3/intake_v2.py">Inspect intake source ↗</a> · <a href="../research/sound-lab-v3/README.md">Usage and limits ↗</a></p>`;const batch=list(state.panel.reviews).find(r=>r.id==='S5B');if(batch?.status==='accepted_narrow')box.insertAdjacentHTML('afterend',`<div class="cli-guide" id="batch-guide"><h4>Compare a complete, preregistered batch</h4><code>python research/sound-lab-v3/batch_intake.py --plan path/to/frozen-plan.json --manifest path/to/acquisition-manifest.json --output path/to/new-analysis-directory</code><p>Use a new output directory. The plan and acquisition manifest must list every trial, order, condition, raw-file hash and predeclared impact time; rejected takes remain in the report. The primary contrast is withheld if a planned trial is missing or ineligible. The shipped plan and manifest are <em>synthetic examples</em>; freeze a separate pilot-informed plan for any real recordings. <a href="../research/sound-lab-v3/S5A/preregistration.json">Example plan ↗</a> · <a href="../research/sound-lab-v3/S5A/trial-template.csv">Trial logging template ↗</a> · <a href="../research/sound-lab-v3/S5B/complete-manifest.json">Example manifest ↗</a> · <a href="../research/sound-lab-v3/batch_intake.py">Inspect batch source ↗</a></p></div>`)}

function sourceRecords(ids){return list(ids).map(id=>[...state.historySources,...state.modernSources,...state.consciousSources,...state.sources].find(s=>s.id===id)).filter(Boolean)}
function sourceHtml(ids){const records=sourceRecords(ids);return records.length?`<div class="source-depth"><strong>Source reading depth</strong><ul>${records.map(s=>`<li>${linkPath(s.url)?`<a href="${escapeHtml(linkPath(s.url))}" target="_blank" rel="noopener noreferrer">${escapeHtml(s.title)}</a>`:escapeHtml(s.title)} · ${escapeHtml(s.depth||s.reading_depth||'Reading depth not supplied')}${s.sections_read?` · sections: ${escapeHtml(list(s.sections_read).join(', '))}`:''}<br>Limit: ${escapeHtml(s.doesNotEstablish||s.does_not_establish||s.does_not_support||'See source record.')}</li>`).join('')}</ul></div>`:list(ids).length?`<p class="source-depth">Source IDs: ${list(ids).map(escapeHtml).join(', ')}. Reading-depth record is pending.</p>`:'<p class="source-depth">No source IDs linked to this entry yet.</p>'}

function artifactsForLoop(r){if(!r)return'';const paths=[
  [r.contractPath,'Frozen contract'],[r.resultsPath,'Numerical results'],[r.reportPath,'Interpretation & limits'],[r.reviewPath,'Independent review'],[r.protocolPath,'Physical protocol'],
  ...list(r.figurePaths||r.figure_path||r.figurePath).map((p,i)=>[p,`Scientific plot ${i+1} · ${r.evidenceType==='actualbytes'?'generated PCM':'synthetic'}`]),
  ...list(r.rawPaths).filter(p=>!String(p).toLowerCase().endsWith('.wav')).map((p,i)=>[p,`Raw model data ${i+1}`])
 ];const wav=list(r.rawPaths).filter(p=>String(p).toLowerCase().endsWith('.wav')).map((p,i)=>linkPath(p)?`<a href="${escapeHtml(linkPath(p))}" download>Download generated WAV fixture ${i+1} · analysis only ↓</a>`:'').join('');return paths.map(([p,label])=>link(p,label)).join('')+wav}

function loopRecord(id){const producer=list(state.sound.loops).find(r=>r.id===id),review=list(state.panel.reviews).find(r=>r.id===id);return producer||review?{...producer,...review,protocolPath:producer?.protocolPath,reviewPath:review?.reviewPath||producer?.reviewPath}:null}
function roundStatus(r){const decision=list(state.panel.reviews).find(x=>x.id===r?.id||x.loop===r?.id);return decision?.status||r?.status||'planned'}
function evidenceTable(r,s){const src=sourceRecords(r.sources||r.sourceIds),names=src.length?src.map(x=>x.title).join('; '):list(r.sources||r.sourceIds).join(', ')||'Source link pending';return `<div class="evidence-table-wrap"><h4>Evidence relations · read the direction</h4><table class="evidence-table"><thead><tr><th>From</th><th>Relationship</th><th>To</th><th>Limit</th></tr></thead><tbody><tr><td>${escapeHtml(names)}</td><td>motivates a test</td><td>${escapeHtml(r.question)}</td><td>A source is not the result.</td></tr><tr><td>${escapeHtml(r.contractPath?'Frozen contract':'Proposed question')}</td><td>tests a declared model</td><td>${escapeHtml(r.scope||r.title)}</td><td>${escapeHtml(r.evidenceType==='actualbytes'?'Generated PCM; no physical mic recording':'Synthetic inputs only')}</td></tr><tr><td>${escapeHtml(r.resultsPath?'Output and raw data':'No output')}</td><td>${escapeHtml(s==='accepted_narrow'?'review supports narrow finding':'awaits independent review')}</td><td>${escapeHtml(r.finding||'No result recorded')}</td><td>${escapeHtml(list(r.withheld||r.limits)[0]||'See the complete review.')}</td></tr></tbody></table></div>`}
function renderLedger(){
 $('#loop-index').innerHTML=soundIds.map((id,i)=>{const r=loopRecord(id),s=roundStatus(r);return `<button type="button" data-loop="${id}" aria-current="${id===state.selected}"><b>${id}</b><span>${r?escapeHtml(r.title):'Question pending'}<small>${escapeHtml(statusLabels[s]||'Planned')}</small></span></button>`}).join('');
 const r=loopRecord(state.selected),s=roundStatus(r);let body;
 if(!r){body=`<p class="empty-note">The preceding loop has not selected and frozen this question. No numerical result or review is available for ${escapeHtml(state.selected)}.</p>`}
 else{
  const limits=list(r.withheld||r.limits||r.limitations),metrics=Object.entries(r.metrics||{}).slice(0,5),fig=list(r.figurePaths)[0];
  const inference=state.setup.find(x=>x.id===(r.id==='S1A'?'S1-identifiability':r.id==='S3B'?'S3B-clock-reference':''));
  body=`<div class="detail-body"><div><h4>${s==='accepted_narrow'?'Narrow finding':s==='executed_pending_review'?'Producer output · pending independent review':'Current record'}</h4><p>${escapeHtml(r.finding||r.result||'No finding recorded.')}</p>${r.scope?`<p class="model-scope"><strong>Tested model:</strong> ${escapeHtml(r.scope)}</p>`:''}${limits.length?`<h4 style="margin-top:19px">What this does not establish</h4><ul>${limits.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:''}${sourceHtml(r.sources||r.sourceIds)}</div><aside><h4>Declared quantities</h4>${metrics.length?metrics.map(([key,value])=>`<p><strong>${escapeHtml(key.replaceAll('_',' '))}</strong><br>${escapeHtml(typeof value==='number'&&Number.isFinite(value)?Number(value).toPrecision(5):value)}</p>`).join(''):'<p>Inputs and results will appear with a frozen contract.</p>'}<p><strong>Evidence type:</strong> ${escapeHtml(r.evidenceType==='actualbytes'?'generated and decoded PCM file, not physical microphone data':r.evidenceType||r.data_kind||'not supplied')}. ${s==='accepted_narrow'?'Accepted only for the stated model.':'No accepted verdict is implied.'}</p></aside></div>${evidenceTable(r,s)}${r.id==='S2A'?'<p class="empty-note">Generated WAV files are analysis fixtures. Some are intentionally silent or full-scale clipped negative controls; they are not listening presets.</p>':''}${inference&&linkPath(inference.file)?`<figure class="research-figure inference"><a href="${escapeHtml(linkPath(inference.file))}"><img src="${escapeHtml(linkPath(inference.file))}" alt="${escapeHtml(inference.alt)}" loading="lazy"></a><figcaption>${escapeHtml(inference.caption)} ${link(inference.file,'Download vector')}</figcaption></figure>`:''}${fig&&linkPath(fig)?`<figure class="research-figure"><a href="${escapeHtml(linkPath(fig))}"><img src="${escapeHtml(linkPath(fig))}" alt="${r.evidenceType==='actualbytes'?'Generated PCM file analysis':'Synthetic scientific plot'} for ${escapeHtml(r.id)}; inspect numerical result and raw data for axis values" loading="lazy"></a><figcaption>${escapeHtml(r.id)} · ${r.evidenceType==='actualbytes'?'generated and decoded PCM fixture; no physical recording':'synthetic model output'}. <a href="${escapeHtml(linkPath(fig))}">Open full-size plot</a>; axes and numeric values are in the linked raw data.</figcaption></figure>`:''}<div class="artifact-list"><h4>Reproduce & inspect</h4><div class="artifact-links">${artifactsForLoop(r)}</div></div>`;
 }
 const preceding=soundIds.indexOf(state.selected)>0?soundIds[soundIds.indexOf(state.selected)-1]:'Planning panels';
 const next=soundIds.indexOf(state.selected)<9?soundIds[soundIds.indexOf(state.selected)+1]:'Conditional B rounds';
 $('#loop-detail').innerHTML=`<div class="detail-top"><span class="eyebrow">${escapeHtml(state.selected)} / round ${Math.ceil((soundIds.indexOf(state.selected)+1)/2)} of 5</span>${status(s)}</div><h3>${escapeHtml(r?.title||'Question awaiting selection')}</h3><p class="detail-question">${escapeHtml(r?.question||'This entry is reserved in the ten-loop sequence. Its contract, model, result and review have not been recorded.')}</p><div class="evidence-lane" aria-label="Research gate"><div><span>Prior evidence</span><p>${escapeHtml(r?.incomingEvidence||preceding)}</p></div><div><span>Critical check</span><p>${escapeHtml(r?.challenge||r?.independentChecks?.factorization_proof||'Read the contract and independent review')}</p></div><div><span>Selected contract</span><p>${r?.contractPath?'Available for inspection':'Not frozen'}</p></div><div><span>Review</span><p>${escapeHtml(statusLabels[s]||'Not recorded')}</p></div><div><span>Next question</span><p>${escapeHtml(r?.nextDecision||`${next} · depends on review`)}</p></div></div>${body}`;
 $('#loop-index').querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{state.selected=button.dataset.loop;renderLedger();if(matchMedia('(max-width:760px)').matches)$('#loop-detail').scrollIntoView({block:'start'})}));
}

function renderB(){
 const container=$('#b-rounds');const cards=bIds.map((id,i)=>{
  const producer=list(state.b.rounds).find(x=>x.id===id),review=list(state.panel.reviews).find(x=>x.id===id),r=producer||review?{...producer,...review}:null,s=roundStatus(r),names=['Shared-cause & target prior','Scoring and selection','Reports and architecture'];
  const figure=r?.figure_path||r?.figurePath||list(r?.figurePaths)[0];
  const artifacts=r?[[r.contract_path||r.contractPath,'Frozen contract'],[r.results_path||r.resultsPath,'Numerical results'],[r.reportPath,'Interpretation'],[r.protocol_path||r.protocolPath,'Proposed protocol'],[review?.reviewPath||review?.review_path,'Independent review'],...list(r.rawPaths).map((p,n)=>[p,`Raw model data ${n+1}`])].map(([p,l])=>link(p,l)).join(''):'';
  const metrics=Object.entries(r?.metrics||{});
  const details=r?`<dl><dt>Tested model</dt><dd>${escapeHtml(r.model||r.hypothesis||'See contract')}</dd><dt>${s==='accepted_narrow'?'Narrow finding':'Producer output · review pending'}</dt><dd>${escapeHtml(r.finding||r.result||'Not recorded')}</dd><dt>Controls</dt><dd>${escapeHtml(list(r.controls).join('; ')||'See frozen contract')}</dd><dt>Limits</dt><dd>${escapeHtml(list(r.withheld||r.limitations||r.limits).join('; ')||'See interpretation')}</dd></dl>${metrics.length?`<div class="b-metric-wrap"><strong>Declared model quantities</strong><table><tbody>${metrics.map(([key,value])=>`<tr><th>${escapeHtml(key.replaceAll('_',' '))}</th><td>${escapeHtml(typeof value==='number'&&Number.isFinite(value)?Number(value).toPrecision(5):value)}</td></tr>`).join('')}</tbody></table></div>`:''}${figure&&linkPath(figure)?`<figure class="b-figure"><a href="${escapeHtml(linkPath(figure))}"><img src="${escapeHtml(linkPath(figure))}" alt="Synthetic ${escapeHtml(id)} methodology figure; numerical axes and values in raw data" loading="lazy"></a><figcaption>Synthetic methodology result, not a human or live-AI observation. ${link(figure,'Open scientific SVG')}</figcaption></figure>`:''}${sourceHtml(r.sources||r.sourceIds)}<div class="artifact-links" style="margin-top:15px">${artifacts}</div>`:'<p>No contract or result has been selected for this entry.</p>';
  return `<article class="b-card"><div class="b-card-header"><span class="eyebrow">${id} / conditional protocol audit</span>${status(s)}</div><h3>${escapeHtml(r?.title||names[i])}</h3><p>${escapeHtml(r?.question||'Reserved after the acoustic sequence. No completed outcome is recorded.')}</p><details><summary>Inspect question, controls & evidence</summary>${details}</details></article>`
 }).join('');container.innerHTML=`<div class="b-context"><p><strong>Premise under examination:</strong> ${escapeHtml(state.b.premise||'A receiver-like or meaning-based account is treated as a conditional hypothesis, not an established mechanism.')}</p><p>Evidence scope: ${escapeHtml(state.b.data_kind||'pending methodology record')}; ${Number(state.b.human_observations||0)} human observations and ${Number(state.b.live_model_calls||0)} live AI experimental calls recorded in this packet.</p><div class="artifact-links">${link('docs/panel-v3/bashar-perspective.md','Attributed source perspective')}${link('research/consciousness-v3/human-ai-protocol.md','Proposed human/AI target protocol')}${link('docs/panel-v3/sources-consciousness.json','Reading-depth source ledger')}</div></div>${cards}`}

function renderSetup(){const entry=state.setup.find(s=>s.id==='S1-bench-plan');if(entry&&linkPath(entry.file)){const frame=$('#apparatus-diagram'),img=frame.querySelector('img');if(img){img.src=linkPath(entry.file);img.alt=entry.alt}frame.querySelector('.diagram-meta span').textContent=entry.caption;const download=$('#diagram-download');download.href=linkPath(entry.file);download.hidden=false}
 const spoon=state.setup.find(s=>s.id==='S2-spoon-plan');if(spoon&&linkPath(spoon.file))$('#secondary-setup').innerHTML=`<details class="secondary-setup"><summary>Optional second apparatus · gentle spoon ringdown</summary><div><figure><img src="${escapeHtml(linkPath(spoon.file))}" alt="${escapeHtml(spoon.alt)}" loading="lazy"><figcaption>${escapeHtml(spoon.caption)} ${link(spoon.file,'Download vector')}</figcaption></figure><div><h3>A household decay recording</h3><ol><li>Suspend an unbroken spoon loosely over a padded table; keep the microphone 0.20 m away without contact.</li><li>Record one second before and at least two seconds after a gentle eraser tap. Retain five separate takes, including poor ones.</li><li>Touch the spoon lightly with a finger for a boundary/damping control. Follow with untouched repeats at unchanged mic position.</li><li>Declare a fit window before comparing decay. Support, room and phone processing can alter the trace.</li></ol><p>This is an unbuilt plan; a good single-mode fit from generated PCM validates the file workflow, not the spoon's intrinsic damping.</p>${link('research/sound-lab-v3/protocol.md','Full step-by-step protocol')}</div></div></details>`;
 const blind=state.setup.find(s=>s.id==='B1-blind-target-flow');if(blind&&linkPath(blind.file))$('#blind-target-setup').innerHTML=`<details class="secondary-setup blind"><summary>Inspect proposed blinded target custody</summary><figure><img src="${escapeHtml(linkPath(blind.file))}" alt="${escapeHtml(blind.alt)}" loading="lazy"><figcaption>${escapeHtml(blind.caption)} ${link(blind.file,'Download vector')}</figcaption></figure></details>`;
 $('#setup-gallery-items').innerHTML=state.setup.filter(x=>linkPath(x.file)).map(x=>`<figure><a href="${escapeHtml(linkPath(x.file))}"><img src="${escapeHtml(linkPath(x.file))}" alt="${escapeHtml(x.alt)}" loading="lazy"></a><figcaption><strong>${escapeHtml(x.title)}</strong><span>${escapeHtml(x.kind)} · ${escapeHtml(x.status)}</span><p>${escapeHtml(x.caption)}</p>${link(x.file,`Open ${x.file.toLowerCase().endsWith('.png')?'full-size PNG':'full-size SVG'}`)}</figcaption></figure>`).join('')}

function renderAlchemy(){const box=$('#alchemy-record'),record=state.alchemy,entries=list(record?.entries);if(!entries.length){box.innerHTML='<p>The source-bound dictionary is not available yet. No historical sample identity is inferred.</p>';return}const group=(title,rows)=>`<h3>${escapeHtml(title)}</h3><div class="table-scroll"><table class="material-table"><thead><tr><th>Historical term</th><th>Candidate modern reading</th><th>Element candidates</th><th>What would distinguish it?</th></tr></thead><tbody>${rows.map(e=>`<tr><td>${escapeHtml(list(e.symbols).join(' '))} ${escapeHtml(e.term)}<small>${escapeHtml(e.mappingStatus.replaceAll('_',' '))}</small></td><td>${escapeHtml(e.modernCandidate||'Unassigned; context required')}<p>${escapeHtml(e.contextLimit)}</p></td><td>${list(e.elements).length?escapeHtml(e.elements.join(', ')):'No justified assignment'}<small>${e.actualSampleAssayed?'Sample assayed':'No historical sample assayed'}</small></td><td>${escapeHtml(e.discriminatingAssay)}<details><summary>Passage and provenance</summary><p>${escapeHtml(e.primaryContext)}</p>${sourceHtml(e.sourceIds)}</details></td></tr>`).join('')}</tbody></table></div>`;
 const conventional=entries.filter(e=>['conventional_mapping_context_pending','primary_context_required'].includes(e.mappingStatus)),ambiguous=entries.filter(e=>!conventional.includes(e));box.innerHTML=`<p>${escapeHtml(record.display_notice||record.scope)}</p>${group('Conventional metal readings · passage context still required',conventional)}${group('Materials, symbols and operations with unresolved identity',ambiguous)}<p class="material-footer">An elemental candidate requires a literal passage and a real specimen to become an assay claim. This dictionary supplies neither a preparation recipe nor a transmutation result. ${link('docs/panel-v3/alchemy-dictionary.json','Download the full dictionary')}</p>`}

function renderSourceIndex(){const box=$('#source-index'),groups=[['Historical texts & nomenclature',state.historySources],['Modern methods & measurements',state.modernSources],['Receiver and AI methodology',state.consciousSources]],seen=new Set();box.innerHTML=`<p>Distinct source records: ${groups.reduce((n,[,entries])=>n+entries.filter(s=>{if(seen.has(s.id))return false;seen.add(s.id);return true}).length,0)}. These are selected readings and explicit leads, not a comprehensive literature search.</p>${groups.map(([name,entries],i)=>`<details class="source-group" ${i===1?'open':''}><summary>${escapeHtml(name)} <span>${entries.length} records</span></summary><div class="source-group-items">${entries.map(s=>`<details class="source-entry"><summary><span>${escapeHtml(s.id)}</span><strong>${escapeHtml(s.title)}</strong><em>${escapeHtml(s.reading_status||'selected reading')}</em></summary><div><p><strong>Read:</strong> ${escapeHtml(s.reading_depth||s.depth||'Reading depth not supplied.')}</p><p><strong>Passages:</strong> ${escapeHtml(list(s.sections_read).join(', ')||'See source ledger.')}</p><p><strong>Supports:</strong> ${escapeHtml(s.supports||'See record.')}</p><p><strong>Does not establish:</strong> ${escapeHtml(s.does_not_support||s.does_not_establish||s.doesNotEstablish||'See record.')}</p><p><strong>Provenance:</strong> ${escapeHtml(s.provenance||s.category||'See record.')}</p>${link(s.url,'Open source')}</div></details>`).join('')}</div></details>`).join('')}<p class="source-ledger-links">${link('docs/panel-v3/sources-history.json','Historical ledger')} ${link('docs/panel-v3/sources-modern.json','Modern ledger')} ${link('docs/panel-v3/sources-consciousness.json','Consciousness ledger')} ${link('research/sound-lab-v3/sources.json','Sound producer packet')}</p>`}

function readWav(buffer){const view=new DataView(buffer),size=view.byteLength;if(size<44||view.getUint32(0,false)!==0x52494646||view.getUint32(8,false)!==0x57415645)throw new Error('Expected a RIFF/WAVE file. Export uncompressed WAV or the CSV format in the protocol.');let format=null,pcm=null;
 for(let pos=12;pos+8<=size;){const id=view.getUint32(pos,false),length=view.getUint32(pos+4,true),begin=pos+8;if(begin+length>size)throw new Error('WAV chunk is truncated. Preserve the original file and export again.');if(id===0x666d7420){if(length<16)throw new Error('WAV format header is incomplete.');format={code:view.getUint16(begin,true),channels:view.getUint16(begin+2,true),sampleRate:view.getUint32(begin+4,true),blockAlign:view.getUint16(begin+12,true),bits:view.getUint16(begin+14,true)}}if(id===0x64617461)pcm={begin,length};pos=begin+length+(length%2)}
 if(!format||!pcm||!format.channels||!format.sampleRate||!format.blockAlign)throw new Error('WAV needs format and data chunks with valid metadata.');if(!((format.code===1&&format.bits===16)||(format.code===3&&format.bits===32)))throw new Error('Only uncompressed PCM16 or float32 WAV is inspected here. Convert a copy and retain the original.');if(format.blockAlign!==format.channels*format.bits/8)throw new Error('WAV channel alignment does not match its declared sample format.');if(pcm.length%format.blockAlign!==0)throw new Error('WAV data ends in a partial sample frame. Preserve the original file and export again.');const n=pcm.length/format.blockAlign;if(n<2)throw new Error('The audio file contains fewer than two frames.');let sum=0,peak=0,clipped=0;for(let i=0;i<n;i++){const off=pcm.begin+i*format.blockAlign,x=format.code===1?view.getInt16(off,true)/32768:view.getFloat32(off,true);if(!Number.isFinite(x))throw new Error('WAV contains non-finite samples.');sum+=x*x;peak=Math.max(peak,Math.abs(x));if(Math.abs(x)>=.999)clipped++}return {format:`WAV · ${format.code===1?'PCM16':'float32'} · channel 1 of ${format.channels}`,sampleRate:format.sampleRate,frames:n,durationS:n/format.sampleRate,peakFS:peak,rmsFS:Math.sqrt(sum/n),clipPercent:100*clipped/n,channelNote:format.channels>1?'Only channel 1 is checked; retain all original channels.':'Single channel.'}}
function readCSV(text){const lines=text.trim().split(/\r?\n/);if(lines.length<3||lines.length>500001)throw new Error('The quick screen accepts a header and 2–500,000 samples. Retain the original and inspect a smaller copy.');const header=lines.shift().replace(/^\uFEFF/,'').split(',').map(x=>x.trim());if(header[0]!=='time_s'||header[1]!=='amplitude_FS')throw new Error('CSV header must begin time_s,amplitude_FS.');let count=0,first=0,previous=-Infinity,last=0,sum=0,peak=0,clipped=0;for(const line of lines){if(!line.trim())continue;const cells=line.split(','),t=Number(cells[0]),x=Number(cells[1]);if(cells.length<2||cells[0].trim()===''||cells[1].trim()===''||!Number.isFinite(t)||!Number.isFinite(x)||t<=previous)throw new Error(`CSV row ${count+2} needs increasing time_s and finite amplitude_FS.`);if(count===0)first=t;previous=t;last=t;count++;sum+=x*x;peak=Math.max(peak,Math.abs(x));if(Math.abs(x)>=.999)clipped++}if(count<2)throw new Error('CSV has fewer than two samples.');return {format:'CSV · amplitude_FS',sampleRate:null,frames:count,durationS:last-first,peakFS:peak,rmsFS:Math.sqrt(sum/count),clipPercent:100*clipped/count,channelNote:'Time spacing and calibration are not verified by this quick check.'}}
function renderIntake(result,file){const flags=[result.clipPercent>0?'Possible clipped samples: inspect original waveform.':'No samples crossed the ±0.999 digital-full-scale screen.',result.rmsFS<.001?'Very quiet relative to digital full scale: check background and source level.':'RMS is a digital level, not pascals or dB SPL.',result.channelNote];$('#intake-result').innerHTML=`<h4>Local metadata screen · ${escapeHtml(file.name)}</h4><div class="intake-metrics"><div><span>Duration</span><strong>${format(result.durationS)} s</strong></div><div><span>Samples checked</span><strong>${result.frames.toLocaleString()}</strong></div><div><span>Peak</span><strong>${format(result.peakFS)} FS</strong></div><div><span>RMS</span><strong>${format(result.rmsFS)} FS</strong></div></div><p>${escapeHtml(result.format)}${result.sampleRate?` · ${result.sampleRate.toLocaleString()} samples/s`:''} · ${format(result.clipPercent)}% samples at clip-screen threshold.</p><ul>${flags.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul><p class="intake-limit">This screen does not align source and receiver clocks, estimate transfer, fit resonance, or measure pressure. A clear flag does not validate the recording chain.</p><div class="artifact-links"><button type="button" id="download-intake">Download metadata (.json)</button><a href="../research/sound-lab-v3/protocol.md">Full protocol ↗</a><a href="../research/sound-lab-v3/README.md">Command-line analysis & reproducibility ↗</a></div>`;const manifest={kind:'local quick screen, not physical calibration',fileName:file.name,fileSizeBytes:file.size,checkedAt:new Date().toISOString(),...result,flags};$('#download-intake').addEventListener('click',()=>download(JSON.stringify(manifest,null,2)+'\n','application/json','sound-recording-screen.json'))}
function installIntake(){const input=$('#recording-file');let generation=0;input.addEventListener('change',async()=>{const token=++generation,file=input.files?.[0];$('#intake-result').innerHTML='<h4>Recording not yet inspected</h4><p>The prior result was cleared. Keep original files and settings.</p>';if(!file){$('#intake-status').textContent='No file selected.';return}$('#intake-status').textContent='Reading the selected file locally…';try{if(file.size>25*1024*1024)throw new Error('This browser quick screen accepts files up to 25 MiB. Retain the original; a smaller copy can be checked here.');const result=/\.wav$/i.test(file.name)?readWav(await file.arrayBuffer()):/\.csv$/i.test(file.name)?readCSV(await file.text()):(()=>{throw new Error('Choose a .wav or .csv file.');})();if(token!==generation)return;renderIntake(result,file);$('#intake-status').textContent='Screen complete. No file was uploaded.'}catch(error){if(token!==generation)return;$('#intake-result').innerHTML='<h4>Recording not inspected</h4><p>The previous result was cleared. Correct the file and try again; retain the original recording.</p>';$('#intake-status').textContent=error.message}})}

function format(v){if(!Number.isFinite(v))return '—';return Math.abs(v)>=100?Math.round(v).toLocaleString():Number(v.toFixed(3)).toString()}
const configs={
 transfer:{name:'Transfer response',description:'Steady-state displacement amplitude of one forced linear oscillator, normalized to its low-frequency response.',fields:[['f0','Natural frequency','Hz',20,5000],['q','Quality factor Q','',.5,50]],formula:'|H(f)| = 1 / √[(1 − (f/f₀)²)² + (f/(Q f₀))²]',caveat:'A peak depends on forcing and damping. This idealized response does not identify the room, object, speaker, or phone separately.',xLabel:'Drive frequency / Hz',yLabel:'Normalized amplitude',sample:x=>x>=0?1/Math.hypot(1-(x/this?.f0)**2,0):0},
 echo:{name:'Echo comb',description:'A direct digital path plus one delayed, scaled copy. Delay and reflection strength are declared inputs.',fields:[['delay','Delay τ','ms',.1,25],['reflection','Delayed amplitude a','',0,.95]],formula:'|H(f)| = |1 + a e^(−i2πfτ)|',caveat:'Periodic notches are consistent with interference under this model; the same total transfer can be assigned to different unknown factors.',xLabel:'Frequency / Hz',yLabel:'Digital amplitude ratio'},
 damping:{name:'Damping envelope',description:'An exponential amplitude envelope for a single underdamped mode; the carrier oscillation is omitted.',fields:[['f0','Undamped natural frequency f₀','Hz',20,5000],['q','Quality factor Q','',.6,60]],formula:'A(t)/A₀ = exp(−πf₀t/Q)',caveat:'The observed damped oscillation frequency differs from f₀, especially at low Q. A measured ringdown may contain multiple modes, room decay, gating, and microphone processing.',xLabel:'Elapsed time / ms',yLabel:'Relative amplitude'},
 reference:{name:'Reference division bound',description:'One frequency bin with a stable complex reference of magnitude |H₀|, bounded noise η in each recording and bounded path change δ.',fields:[['h0','Reference magnitude |H₀|','digital ratio',.0001,1],['noise','Noise bound η','digital ratio',0,1],['drift','Path-change bound δ','digital ratio',0,1]],formula:'|R̂ − 1| ≤ (δ + 2η) / (|H₀| − η), when η < |H₀|',caveat:'A bound on complex-ratio error under declared per-record noise and path-change bounds. It does not identify the source of drift or calibrate a phone.',xLabel:'Noise bound η / digital ratio',yLabel:'Worst-case ratio-error bound'}
};
delete configs.transfer.sample;

function modelRows(kind,p){let maxX,sample,result;
 if(kind==='transfer'){maxX=Math.min(6000,Math.max(1000,p.f0*2.5));sample=x=>1/Math.hypot(1-(x/p.f0)**2,x/(p.q*p.f0));result=`At f₀ = ${format(p.f0)} Hz, amplitude ratio = Q = ${format(p.q)} in this normalization.`}
 else if(kind==='echo'){maxX=Math.min(4000,Math.max(500,4*1000/p.delay));sample=x=>Math.hypot(1+p.reflection*Math.cos(2*Math.PI*x*p.delay/1000),p.reflection*Math.sin(2*Math.PI*x*p.delay/1000));result=p.reflection===0?'No delayed path: flat amplitude ratio 1. A comb spacing or minimum is not observable in this null control.':`Comb spacing = ${format(1000/p.delay)} Hz; first ideal minimum = ${format(500/p.delay)} Hz.`}
 else if(kind==='damping'){maxX=Math.min(300,Math.max(15,5*1000*p.q/(Math.PI*p.f0)));sample=x=>Math.exp(-Math.PI*p.f0*(x/1000)/p.q);result=`Amplitude e-fold time = ${format(1000*p.q/(Math.PI*p.f0))} ms.`}
 else{maxX=Math.min(.95*p.h0,Math.max(.2*p.h0,1.25*p.noise));sample=x=>(p.drift+2*x)/(p.h0-x);result=`At η = ${format(p.noise)}, the worst-case ratio-error bound is ${format(sample(p.noise))}. This bound requires η < |H₀|.`}
 const rows=Array.from({length:241},(_,i)=>{const x=maxX*i/240;return{x,y:sample(x)}});return {rows,result,maxX}
}
function plotSvg(kind,rows,xLabel,yLabel){const W=760,H=340,left=70,right=24,top=37,bottom=58;const maxY=Math.max(1,...rows.map(r=>r.y))*1.07,spanX=W-left-right,spanY=H-top-bottom;
 const sx=x=>left+spanX*x/rows.at(-1).x,sy=y=>top+spanY*(1-y/maxY),line=rows.map((r,i)=>`${i?'L':'M'}${sx(r.x).toFixed(2)} ${sy(r.y).toFixed(2)}`).join(' ');
 const ticks=[0,.25,.5,.75,1];return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="Synthetic model output, ${escapeHtml(xLabel)} against ${escapeHtml(yLabel)}. ${rows.length} calculated points; numeric samples and CSV download follow."><rect width="${W}" height="${H}" fill="#fff"/><text x="${left}" y="22" fill="#315b43" font-size="13" font-family="sans-serif">SYNTHETIC MODEL OUTPUT · ${escapeHtml(kind.toUpperCase())}</text>${ticks.map(t=>`<path class="grid" d="M${left} ${sy(maxY*t)}H${W-right}"/><text x="${left-11}" y="${sy(maxY*t)+4}" text-anchor="end">${format(maxY*t)}</text><path class="grid" d="M${sx(rows.at(-1).x*t)} ${top}V${H-bottom}"/><text x="${sx(rows.at(-1).x*t)}" y="${H-bottom+18}" text-anchor="middle">${format(rows.at(-1).x*t)}</text>`).join('')}<path class="axis" d="M${left} ${top}V${H-bottom}H${W-right}" fill="none"/><path class="curve" d="${line}"/><text x="${(left+W-right)/2}" y="${H-12}" text-anchor="middle">${escapeHtml(xLabel)}</text><text x="12" y="${top+8}">${escapeHtml(yLabel)}</text></svg>`}

function renderModel(){const kind=state.model,c=configs[kind],values=state.values[kind];$('#model-tabs').querySelectorAll('button').forEach(b=>{const active=b.dataset.model===kind;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});$('#model-panel').setAttribute('aria-labelledby',`tab-${kind}`);
 $('#model-panel').innerHTML=`<div class="model-content"><form class="model-controls" id="model-form" novalidate><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.description)}</p>${c.fields.map(([id,label,unit,min,max])=>`<label class="field" for="model-${id}">${escapeHtml(label)}<span class="input-wrap"><input id="model-${id}" name="${id}" type="number" step="any" required min="${min}" max="${max}" value="${escapeHtml(values[id])}" inputmode="decimal"><span>${escapeHtml(unit)}</span></span><span class="field-hint">${min}–${max}${unit?' '+unit:''}</span></label>`).join('')}<button class="button primary" type="submit">Calculate ${escapeHtml(c.name.toLowerCase())}</button><p class="model-error" id="model-error" role="status"></p></form><div class="model-results"><span class="model-label">synthetic model output / no fitted recording</span><h3 id="model-result-title">Calculated trace</h3><p>${escapeHtml(c.caveat)}</p><div class="plot-wrap" id="plot-wrap"></div><p class="result-line" id="result-line"></p><div class="formula">${escapeHtml(c.formula)}</div><p id="model-assumptions"></p><div class="export-row"><button type="button" id="download-csv">Download values (.csv)</button><button type="button" id="download-svg">Download plot (.svg)</button></div><table class="data-points" aria-label="Five representative model points"><thead><tr><th>${escapeHtml(c.xLabel)}</th><th>${escapeHtml(c.yLabel)}</th></tr></thead><tbody id="model-table"></tbody></table></div></div>`;
 $('#model-form').addEventListener('submit',e=>{e.preventDefault();calculateModel()});calculateModel();}
let currentExport=null;
function calculateModel(){const kind=state.model,c=configs[kind],p={};try{for(const [key,label,unit,min,max] of c.fields){const input=$(`#model-${key}`),value=Number(input.value);if(input.value.trim()===''||!input.checkValidity()||!Number.isFinite(value)||value<min||value>max)throw new RangeError(`${label} must be between ${min} and ${max}${unit?' '+unit:''}.`);p[key]=value}if(kind==='reference'&&p.noise>=p.h0)throw new RangeError('Noise bound η must be smaller than reference magnitude |H₀|; the denominator has no positive lower bound.');const {rows,result}=modelRows(kind,p);if(rows.some(r=>!Number.isFinite(r.y)))throw new RangeError('The model output is not finite at these settings.');state.values[kind]=p;const svg=plotSvg(kind,rows,c.xLabel,c.yLabel);$('#plot-wrap').innerHTML=svg;$('#result-line').textContent=result;$('#model-assumptions').textContent=`Assumed inputs: ${c.fields.map(([key,label,unit])=>`${label} = ${p[key]}${unit?' '+unit:''}`).join('; ')}. No measured value was entered.`;$('#model-table').innerHTML=[0,60,120,180,240].map(i=>`<tr><td>${format(rows[i].x)}</td><td>${format(rows[i].y)}</td></tr>`).join('');$('#model-error').textContent='';currentExport={kind,svg,rows,p,xLabel:c.xLabel,yLabel:c.yLabel};}
 catch(error){currentExport=null;$('#plot-wrap').innerHTML='';$('#result-line').textContent='';$('#model-assumptions').textContent='';$('#model-table').innerHTML='';$('#model-error').textContent=error.message}}
function download(content,type,name){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function installModelEvents(){const tabs=$('#model-tabs');tabs.addEventListener('click',e=>{const button=e.target.closest('button[data-model]');if(button){state.model=button.dataset.model;renderModel()}});tabs.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const names=Object.keys(configs),index=names.indexOf(state.model),next=e.key==='Home'?0:e.key==='End'?names.length-1:(index+(e.key==='ArrowRight'?1:-1)+names.length)%names.length;state.model=names[next];renderModel();$(`#tab-${state.model}`).focus()});$('#model-panel').addEventListener('click',e=>{if(!currentExport)return;if(e.target.id==='download-svg')download(currentExport.svg,'image/svg+xml',`sound-${currentExport.kind}-synthetic.svg`);if(e.target.id==='download-csv'){const d=currentExport;const meta=`# synthetic model output; no physical measurement\n# model=${d.kind}; parameters=${JSON.stringify(d.p)}\n# x=${d.xLabel}; y=${d.yLabel}\n`;download(meta+`x,y\n${d.rows.map(r=>`${r.x.toPrecision(12)},${r.y.toPrecision(12)}`).join('\n')}\n`,'text/csv',`sound-${d.kind}-synthetic.csv`)}})}
installModelEvents();installIntake();renderModel();loadResearch();
