from pathlib import Path
import sys,json
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from common import *
p=Path(__file__).parent;f=500;c=343;k=2*np.pi*f/c;lam=c/f;coeff=np.array([1,.6*np.exp(.7j)]);partner=np.conj(coeff[::-1]);x=np.linspace(0,1,1001)
def matrix(x):return np.column_stack([np.exp(-1j*k*np.asarray(x)),np.exp(1j*k*np.asarray(x))])
field=matrix(x)@coeff;alt=matrix(x)@partner;rot=field*np.exp(.9j);M1=matrix([0]);M2=matrix([0,lam/4]);kernel=np.array([1,-1]);z=M2@coeff;fit=np.linalg.solve(M2,z)
metrics={'magnitude_partner_max_error':float(np.max(np.abs(np.abs(field)**2-np.abs(alt)**2))),'common_phase_magnitude_max_error':float(np.max(np.abs(np.abs(field)**2-np.abs(rot)**2))),'single_complex_domain_dimension':2,'single_complex_rank':int(np.linalg.matrix_rank(M1)),'single_complex_nullity':2-int(np.linalg.matrix_rank(M1)),'kernel_residual':float(np.linalg.norm(M1@kernel)),'two_sample_rank':int(np.linalg.matrix_rank(M2)),'two_sample_nullity':2-int(np.linalg.matrix_rank(M2)),'two_sample_condition':float(np.linalg.cond(M2)),'two_sample_coefficient_error':float(np.max(np.abs(fit-coeff))),'wavelength_m':lam,'quarter_wavelength_m':lam/4,'coefficient_ratio_original':float(abs(coeff[1]/coeff[0])),'coefficient_ratio_partner':float(abs(partner[1]/partner[0]))}
assert metrics['magnitude_partner_max_error']<1e-12 and metrics['common_phase_magnitude_max_error']<1e-12 and metrics['kernel_residual']<1e-12 and metrics['two_sample_coefficient_error']<1e-12
csv(p/'spatial_response.csv',['position_m','p_real','p_imag','partner_real','partner_imag','magnitude_squared','partner_magnitude_squared','rotated_real','rotated_imag'],np.column_stack([x,field.real,field.imag,alt.real,alt.imag,abs(field)**2,abs(alt)**2,rot.real,rot.imag]));csv(p/'observations.csv',['position_m','p_real','p_imag'],np.column_stack([[0,lam/4],z.real,z.imag]));writejson(p/'inverse_structure.json',{'field':'complex','domainDimension':2,'singleObservation':{'rank':1,'nullity':1,'kernelWitness':[[1,0],[-1,0]]},'twoObservations':{'rank':2,'nullity':0,'positions_m':[0,lam/4]},'coefficients':[[v.real,v.imag]for v in coeff],'partnerCoefficients':[[v.real,v.imag]for v in partner]})
fig,ax=plt.subplots(2,1,figsize=(9,6));ax[0].plot(x,abs(field)**2,label='Original');ax[0].plot(x,abs(alt)**2,'--',label='Conjugate/swap partner');ax[0].set(ylabel='Squared normalized magnitude',title='Synthetic magnitude maps overlap despite different traveling coefficients');ax[0].legend();ax[1].plot(x,field.imag,label='Original imaginary part');ax[1].plot(x,alt.imag,'--',label='Partner imaginary part');ax[1].axvline(lam/4,color='gray',ls=':');ax[1].set(xlabel='Position (m)',ylabel='Normalized complex component',title='A shared phase reference carries additional information');ax[1].legend();savefig(fig,p/'figure.svg')
finish(p,metrics,'Dense magnitude samples retain exact phase/direction ambiguities; two appropriately spaced complex samples recover the declared model coefficients with a shared phase reference.',[{'control':'Infer traveling direction or material from magnitude map alone','outcome':'rejected without additional directional/boundary premises'},{'control':'Treat a single positive singular value as injectivity','outcome':'rejected: domain2,rank1,nullity1 with kernel[1,-1]'}],'''# S4A — more pixels are not necessarily more information

For the declared two-wave model, exchanging and conjugating coefficients conjugates the entire spatial field. Its squared magnitude is unchanged at every position, not merely at the sampled1001 points. Multiplying both coefficients by any common phase is another magnitude-invisible operation. A visually elaborate nodal or magnitude pattern therefore cannot alone establish a unique wave direction, phase, source, or material.

The single complex observation at x=0 maps a2-dimensional complex coefficient space to one scalar. Its rank is1 and nullity1; [1,-1] is an exact kernel witness. Two complex observations at0 and lambda/4 have rank2, nullity0 and condition1, so they reconstruct the two coefficients in this model.

The conjugate/swap partner has a reversed larger traveling component. If incident direction is independently fixed and a passive reflection constraint |B/A|≤1 applies, that partner is excluded; this extra information must be stated. Common phase remains invisible to magnitude alone. A sequential phone amplitude survey does not automatically provide the shared phase reference needed for complex inversion. Next: finite positioning/noise and phase-reference error can destabilize this ideal inverse.
''',['spatial_response.csv','observations.csv','inverse_structure.json','figure.svg'])
